### ISSUE TITLE
Restucture the Project directory

### ISSUE THREAD

**Issue by eeshadutta** [OpenHumans/oh-proj-management#24]
As the project grows and we add newer apps, it would be better to separate project files like manage.py from files like LICENSE, .gitignore, README.md.
For this, another folder can be created which would have the entire Django application and on the outside files not interfering with the code base can be placed.
I would like to work on this issue.

**Comment by eeshadutta** [comment]
Few of the other Open Source projects have a similar structure where the core code base of the application is in one folder and the README, LICENSE, pipfile etc are outside.

For example, the Systers portal has separate folder for the main folder https://github.com/systers/portal

**Comment by akshitac8** [comment]
@eeshadutta Is this bug up for solving?

**Comment by mcescalante** [comment]
As this repo grows, we may choose to restructure it, but for now I think that it is okay following the same structure that we've been using on other projects thus far. I'm going to close this and when the time comes for some restructuring we'll open a new issue 😄
