### ISSUE TITLE
Make the code flake8 compliant

### ISSUE THREAD

**Issue by eeshadutta** [OpenHumans/oh-proj-management#25]
To keep the project clean and prevent things like bad formatting, incorrect styling, it would be useful to add flake8 to the requirements and run flake8 every time someone pushes their code to the Project.

I would like to add this to the project.

**Comment by mcescalante** [comment]
Closed with https://github.com/OpenHumans/oh-proj-management/commit/5003fcf665232dd1c5d868147f5f663a9e770b7d
