### ISSUE TITLE
Add app for `project-admin`

### ISSUE THREAD

**Issue by madprime** [OpenHumans/oh-proj-management#3]
The current code is structured with `views.py` is in the main "project-wide" app `oh_proj_management`.

Let's use `startapp` to create a new app in the Django project called `project_admin` and move the `views.py` and associated logic (e.g. `forms.py` and `templates` directory) to be within the new app. (And in the future, this `project_admin` app can be where additional stuff, e.g. `models.py`, is created.)

**Comment by fiennyangeln** [comment]
Hi I have created the project_admin app. Please check if I do it correctly. Thx.

**Comment by gedankenstuecke** [comment]
Closed by #11
