### ISSUE TITLE
Add null=True for project badge image in models

### ISSUE THREAD

**Issue by mcescalante** [OpenHumans/oh-proj-management#37]
## Description

On [line 10](https://github.com/OpenHumans/oh-proj-management/blob/master/project_admin/models.py#L10) in the models we have `blank=True` but not `null=True`. I have created a project without a badge and tried entering the master token. When I enter the token, I get an error `NOT NULL constraint failed`. Adding `null=True` and migrating should fix this, but I have not confirmed.

## Acceptance Criteria

- Reproduce the error `NOT NULL constraint` with a badge-less project
- Add null=True and verify that fixes the issue
- Consider writing a test for this _(not required)_

**Comment by aashaka** [comment]
I would like to take this up!

**Comment by mcescalante** [comment]
@aashaka there's a PR open (#38) already on this, so you may want to wait for that to be reviewed!

**Comment by aashaka** [comment]
Sure!

**Comment by mcescalante** [comment]
Closed with #38 and https://github.com/OpenHumans/oh-proj-management/commit/c527f1e0ee32666f4b3199807ace47fbb0cbb641
