### ISSUE TITLE
Retrieve and display project-level information

### ISSUE THREAD

**Issue by madprime** [OpenHumans/oh-proj-management#4]
Update `HomeView` to ~~use the Open Humans API project information endpoint ([at the bottom of this page](https://www.openhumans.org/direct-sharing/on-site-data-access/#api-project-info)) and retrieve project information.~~

~~Pass this information to context and~~ display the project title (and maybe more information about the project?) in `home.html`

**Comment by kritisingh1** [comment]
Can I take this up? Thanks!

**Comment by madprime** [comment]
Sounds good to me!

**Comment by madprime** [comment]
Note: with the addition of a Project model (#14) this issue should now be using the Project model instead of pulling data from the API. I've updated my initial comment to reflect this.
