### ISSUE TITLE
Add annotations/notes for project member

### ISSUE THREAD

**Issue by mcescalante** [OpenHumans/oh-proj-management#40]
We would like to allow the creation of notes/annotations for project members. [See this issue for a bit more discussion](https://github.com/OpenHumans/open-humans/issues/657).

To start, it is OK if this notes/annotations field is just a single field that allows a project admin to keep notes about specific project members.

## Acceptance criteria

- Add the appropriate models for storing notes/annotations about a project member
- Modify / create any views necessary to allow administrators to create/edit/update these annotations.

**Comment by Sanny26** [comment]
I'm working on this issue.

**Comment by rosygupta** [comment]
@Sanny26 are you working on this? If not, I'd like to get on it :)

**Comment by shubhangi-chauhan** [comment]
@rosygupta Can you share your thoughts? I think we should discuss this first since it might conflict with https://github.com/OpenHumans/oh-proj-management/pull/43

**Comment by rosygupta** [comment]
@shubhangi-chauhan I was waiting for your PR to be approved since this one has a dependency on that. Once its approved, I believe there won't be any conflict :) I'll work on this only then.

**Comment by rosygupta** [comment]
For now, I have worked on the UI part. Rest I'll complete after your PR gets merged.

**Comment by shubhangi-chauhan** [comment]
Haha yeah that's okay, I just wanted to check if the model I've written is suitable for the implementation you have in mind for this issue.

**Comment by shubhangi-chauhan** [comment]
Haha yeah that's okay, I just wanted to check if the model I've written is suitable for the implementation you have in mind for this issue since that's not merged yet.

**Comment by sflorencia** [comment]
Can i work on this issue?

**Comment by rosygupta** [comment]
@sflorencia I'm about to create a PR for it :)

**Comment by rosygupta** [comment]
Closed via #59
