### ISSUE TITLE
Add a model for project data

### ISSUE THREAD

**Issue by madprime** [OpenHumans/oh-proj-management#5]
We can use the Open Humans API's [project information endpoint](https://www.openhumans.org/direct-sharing/on-site-data-access/#api-project-info) to identify what project ID a master token refers to.

Create a `Project` model in this Django app with fields corresponding to this information. Treat the project's ID returned by the API as a unique identifier of the project.

Modify LoginView to immediately use the master token to query the API, and then either (1) create/save a new Project in the database if one doesn't already exist, or (2) update information for a Project in the database, if it already exists.

**Comment by eeshadutta** [comment]
Hi @madprime can I take up this issue?

**Comment by madprime** [comment]
Hi @eeshadutta, you're welcome to work on this!

If you would like to open a PR to get feedback partway through, please title it "WIP" at the beginning (e.g. "WIP Adding feature foobar"). (This stands for "Work in progress" and indicates that it's not intended to be merged yet. The PR gives us a place to comment on work-in-progress.)

Also, be sure to reference this issue in the PR!

**Comment by rosygupta** [comment]
Hello @madprime, 

As I looked through the project data endpoint, I encountered the need for some special data types which brought me to the point as to what should be the default database? I see that Open Humans main repository uses Postgres and might as well be good to have consistency. Look forward to your valuable feedback. :)

**Comment by gedankenstuecke** [comment]
@rosygupta Which special data types are you looking for? 😃 

If you look at the [`settings.py`](https://github.com/OpenHumans/oh-proj-management/blob/master/oh_proj_management/settings.py#L112) you will see that the default here is sqlite if you develop locally, but if it's deployed to `heroku` it will grab the settings from there, which defaults to Postgres.

**Comment by rosygupta** [comment]
Hi, @gedankenstuecke  I was looking for a list data type and thought the only way was `ArrayField` (via postgres). But I didn't check properly I guess. We could use `ListField` too, right? 

Also, the recent addition of `project` model to the code doesn't include the conditions for the data fields as per the project data. For instance, all fields are currently mandatory  which causes errors like 
`IntegrityError at /login NOT NULL constraint failed: project_admin_project.badge_image`.

Also, fields like `Requested sources` is a list (unlike in the current model), for which I was looking for a specific data type.

**Comment by gedankenstuecke** [comment]
Hey @rosygupta! Thanks for noticing these things! 

I'm not sure about the `ListField` (I have to admit to not have heard about this one) but if there's one that's supported across databases that would be great. Otherwise one can dump a `JSON` into a TextField, that's what I did for https://github.com/gedankenstuecke/oh_data_uploader (see https://github.com/gedankenstuecke/oh_data_uploader/blob/master/project_admin/models.py#L31). This way all databases can handle the lists. 

Could you open the issues for these bugs that you report (and if you want even work on solutions for them?)

**Comment by rosygupta** [comment]
@gedankenstuecke Sure will raise an issue. Would to work on them as well. 

Your way of dumping as JSON is good. The ListField is specific to MySQL again (#mybad). But is there any specific reason for having a universal code for all databases (like an ORM)? Is it so as to make contributions easier?

**Comment by gedankenstuecke** [comment]
@rosygupta Thanks, that's so great! 🎉 

Having the universal code makes it easier not only to contribute but also to deploy it, as people can use the database-backend of their choice when deploying the application on their end and are not forced to use Postgres. For that reason I'd avoid database specific-code as much as possible 

(having said this, there are good reasons to choose a more advanced database for specific use-cases, but I don't think the project management application will become so complex that it will be one of these cases)
