### ISSUE TITLE
Use login and User accounts

### ISSUE THREAD

**Issue by madprime** [OpenHumans/oh-proj-management#6]
Problem: The current project "logs in" using the master token and storing it as session data. This is a hack.

What we want: the master token can be used to log in a User. That is to say: instead of hacking session data to hold the master token (to create a persistent "login"), we should use Django's standard method for logging in: permanent User accounts associated with each Project.

Map Django's User object as a a one-to-one field to Project. Update `LoginView` to create a new User when a new Project is created (the username should probably be related to the project ID, e.g. using the `id_label` returned by the API).

Then, use the master token to identify the Project and corresponding User, and use the following command to log a User in:

```
from django.contrib.auth import login

login(request, user, backend='django.contrib.auth.backends.ModelBackend')
```

**Comment by rosygupta** [comment]
Hi @madprime, I'd like to start working on this. :)

**Comment by madprime** [comment]
I think that's fine -- part of the purpose is to demonstrate skill, you
wouldn't prevent that, so not a reason to block on it? And as this project
grows it'll be easier to create more features/issues that aren't blocking
on each other. :)

**Comment by rosygupta** [comment]
Also can I suggest certain features which I think would be valuable to the repo?

**Comment by madprime** [comment]
Absolutely, please do!

**Comment by fiennyangeln** [comment]
Hi @madprime is there any more issue I could work on?

**Comment by eeshadutta** [comment]
@madprime 
I would like to try working on this issue, Just confirming the flow of user interaction.
The user is first required to enter the token. If the project corresponding to this token exists, then the user is redirected to home page, else the user would be redirected to sign up page where he enters required details and is subsequently redirected to the home page. Is this correct?

**Comment by madprime** [comment]
No, no new information is taken from Users beyond the token. New things to do are in bold...

**Add a OneToOne field to the Project model corresponding to Django's built in User.** See: https://docs.djangoproject.com/en/2.0/topics/auth/customizing/#extending-the-existing-user-model

User/app login process:
1. User enters token
2. App uses the token to retrieve project data via API
3. If project exists, retrieve it (using the `id` parameter). Also, update project info. If it doesn't exist, create a new one **and simultaneously create a corresponding User object.** See:
https://docs.djangoproject.com/en/2.0/topics/auth/default/#creating-users
4. **Log in the Project's corresponding user using the login command noted above (i.e. with the backend, which allows you to bypass password authentication).**

You can also:
* **Remove all session-based data storage. `request.user` will identify a logged in user now.**
* **Add a log out button.**

(But it's probably OK if one or both of those items are left for another issue.)
