### ISSUE TITLE
Member files are only added, not removed

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/oh-proj-management#61]
<img width="1067" alt="screen shot 2018-06-04 at 10 26 17" src="https://user-images.githubusercontent.com/674899/40931960-c62974f4-67e1-11e8-9ac7-908c84b7020b.png">

Right now the `/members/` slug looks for new files for each project member. But it never checks for files which are already in our database but that aren't available any more on Open Humans. Above is an example: 

This user (aka me) has exactly one current `rescuetime.json` in their account. But as this file is periodically updated (by replacing it & thus creating a new file ID) each update is added to the `oh-proj-management` view (which is the correct behaviour). But the old files, which have been deleted on Open Humans, aren't removed from the `/members/` view.

Proposed fix: When updating the file list the `view` should also check which existing files in our database aren't in the returned `open humans API object` any more and delete the references to them.

**Comment by rosygupta** [comment]
Closed via #66
